### ISSUE TITLE
不错的项目 准备学习下 

### ISSUE THREAD

**Issue by BestDingSheng** [eidonlon/imitate-One#1]
nodejs 部署到服务区还不太懂 能加个微信 交流下吗 ~

**Comment by eidonlon** [comment]
@BestDingSheng 我写了一个关于怎么把vue项目部署到Node服务器的小教程，你可先看一下对你有帮助没，地址：http://www.jianshu.com/p/ce8766f3e68d

**Comment by BestDingSheng** [comment]
谢谢，跟着教程已经把项目部署到哪个云平台了 这几天自己在研究下 3q ~

**Comment by eidonlon** [comment]
@BestDingSheng 啊哈，很高兴你觉得有用。
